# Generated by Django 2.2.5 on 2020-03-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('Rid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('User', models.EmailField(max_length=15)),
                ('Pass', models.CharField(max_length=15)),
                ('Gen', models.CharField(max_length=1)),
                ('College', models.CharField(max_length=30)),
                ('Mobile', models.ImageField(max_length=10, upload_to='')),
            ],
        ),
    ]
