# Generated by Django 2.2.5 on 2020-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='User',
            field=models.EmailField(max_length=50),
        ),
    ]
