# Generated by Django 2.2.5 on 2020-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20200314_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrations',
            old_name='User',
            new_name='Email',
        ),
    ]
