# Generated by Django 2.2.5 on 2020-03-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='Gen',
        ),
        migrations.AddField(
            model_name='registrations',
            name='Gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
