# Generated by Django 2.2.5 on 2020-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20200315_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrations',
            old_name='Pass',
            new_name='Password',
        ),
        migrations.AlterField(
            model_name='registrations',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
    ]
