# Generated by Django 2.2.5 on 2020-03-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('Qtype', models.CharField(max_length=10)),
                ('Qdes', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=100)),
            ],
        ),
    ]
