# Generated by Django 2.2.5 on 2020-03-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_login'),
        ('Exam', '0002_auto_20200315_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Testid', models.AutoField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=30)),
                ('Qpapertype', models.CharField(max_length=10)),
                ('Maxmarks', models.IntegerField(max_length=3)),
                ('Obtmarks', models.IntegerField(max_length=3)),
                ('Result', models.CharField(max_length=10)),
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Registrations')),
            ],
            options={
                'db_table': 'Test',
            },
        ),
    ]
