# Generated by Django 2.2.5 on 2020-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Maxmarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='test',
            name='Obtmarks',
            field=models.IntegerField(),
        ),
    ]
