# Generated by Django 2.2.5 on 2020-03-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0004_auto_20200319_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='select',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
