# Generated by Django 2.2.5 on 2020-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0005_question_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='NoofRightAnswer',
            field=models.IntegerField(default=0),
        ),
    ]
