# Generated by Django 2.2.5 on 2020-03-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam', '0006_test_noofrightanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='Date',
            field=models.DateField(default='2020-03-01'),
        ),
    ]
